[pytest]
# Tell pytest where it is allowed to look for tests
testpaths = v2_upgraded/tests

# Explicitly add the root to python path to eliminate module pathing issues
pythonpath = .

# Ensure pytest captures and outputs for our capsys verification tests
addopts = -v