apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: stream-pipeline
data:
  AWS_DEFAULT_REGION: us-east-2
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_HEADLESS: "true"
